export const categories = [
  "Women's Fashion",
  "Men's Fashion",
  'Sports',
  'Toys & Games',
  'Books',
  'Beauty & Personal Care',
  'Furniture',
  'Groceries',
  'Outdoor Gear',
  'Home Appliances',
  'Health & Fitness',
  'Electronics',
  'Home Decor',
  'Gaming',
  'Kitchen Appliances',
  'Watches',
  'Kitchenware',
  'Accessories',
  'Bags',
  'Fitness',
  'Health & Beauty',
  'Footwear',
  'Apparel',
];
